name: Lock Bug Issues

on:
  issues:
    types: [opened]

jobs:
  lock:
    runs-on: ubuntu-latest

    steps:
      - name: Lock bug issue
        if: contains(github.event.issue.title, '[BUG-FORM]')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BUG_REPORT_TOKEN }}
          script: |
            await github.rest.issues.lock({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              lock_reason: "off-topic"
            })
